// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_unit.sql

package store

import (
	"context"
)

const listMunicipalityGeometry = `-- name: ListMunicipalityGeometry :many

SELECT code, name, ST_AsGeoJSON(geom)::text AS geojson
FROM admin_unit
WHERE unit_kind = 'municipality'
ORDER BY code
`

type ListMunicipalityGeometryRow struct {
	Code    string `json:"code"`
	Name    string `json:"name"`
	Geojson string `json:"geojson"`
}

// 色分け配信（ADR-0016 初手＝ST_AsGeoJSON）の形クエリ。値は別経路ゆえここは形だけ。
// ST_AsGeoJSON(geom)::text はテキストを返す（geometry 型の特別扱い不要）。FeatureCollection の
// 組み立ては Go 側で行い、geojson 列は生 JSON としてそのまま埋める（二重エンコードしない・handler）。
// 静的クエリゆえ sqlc 既定（backend-conventions §1.1）。
func (q *Queries) ListMunicipalityGeometry(ctx context.Context) ([]ListMunicipalityGeometryRow, error) {
	rows, err := q.db.Query(ctx, listMunicipalityGeometry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMunicipalityGeometryRow
	for rows.Next() {
		var i ListMunicipalityGeometryRow
		if err := rows.Scan(&i.Code, &i.Name, &i.Geojson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
