// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metric_value.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMetricValues = `-- name: ListMetricValues :many

SELECT unit_id AS code, value, status
FROM metric_value
WHERE metric = $1
  AND unit_kind = $2
ORDER BY unit_id
`

type ListMetricValuesParams struct {
	Metric   string `json:"metric"`
	UnitKind string `json:"unit_kind"`
}

type ListMetricValuesRow struct {
	Code   string        `json:"code"`
	Value  pgtype.Float8 `json:"value"`
	Status string        `json:"status"`
}

// 値配信（ADR-0016 (i) 値とジオメトリの分離）の値クエリ。形は別経路（geometry）ゆえここは値だけ。
// GET /api/choropleth/values?metric=<key> が指定 metric の全単位を返し、FE は setFeatureState で
// feature.id（5桁コード）へ結合して塗る。data_status を一緒に返し「データなし3区別」を FE まで運ぶ
// （ADR-0011・色抜き判定に使う）。
// 静的クエリ（実行時に形が変わらない・metric/unit_kind は値の差し替えのみ）ゆえ sqlc 既定（backend-conventions §1.1）。
// unit_kind を引数に取るのはメッシュ移行の継ぎ目（ADR-0015）：'municipality'↔'mesh250' を呼び分けるだけで同じ表が効く。
func (q *Queries) ListMetricValues(ctx context.Context, arg ListMetricValuesParams) ([]ListMetricValuesRow, error) {
	rows, err := q.db.Query(ctx, listMetricValues, arg.Metric, arg.UnitKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetricValuesRow
	for rows.Next() {
		var i ListMetricValuesRow
		if err := rows.Scan(&i.Code, &i.Value, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
