// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

type AdminUnit struct {
	Code     string      `json:"code"`
	UnitKind string      `json:"unit_kind"`
	Name     string      `json:"name"`
	PrefCode string      `json:"pref_code"`
	Geom     interface{} `json:"geom"`
}
